services:
  web:
    build: .
    container_name: web_app
    ports:
      - "5001:5001"  # Maps host port 8080 to container port 8080 (adjust as needed)
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - ENV=dev

  mongo:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"  # Expose MongoDB's default port
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
